# Generated by Django 4.2.10 on 2025-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0004_alter_user_balance_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=22, unique=True)),
                ('refer', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(default='user', max_length=20)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('caste', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('aadhar', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pic', models.ImageField(blank=True, default='User_Pic/profilepic.jpg', null=True, upload_to='User_Pic')),
                ('disttrict', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('like', models.JSONField(blank=True, default=list)),
                ('create_date', models.DateField(auto_now=True)),
                ('user_apply', models.JSONField(blank=True, default=list)),
                ('marrige_status', models.CharField(blank=True, max_length=10, null=True)),
                ('university', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.CharField(blank=True, max_length=30, null=True)),
                ('job_title', models.CharField(blank=True, max_length=20, null=True)),
                ('job_type', models.CharField(blank=True, max_length=30, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=30, null=True)),
                ('brother', models.IntegerField(blank=True, null=True)),
                ('brother_marrige', models.IntegerField(blank=True, null=True)),
                ('sister', models.IntegerField(blank=True, null=True)),
                ('sister_marrige', models.IntegerField(blank=True, null=True)),
                ('ref', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='brother',
        ),
        migrations.RemoveField(
            model_name='user',
            name='brother_marrige',
        ),
        migrations.RemoveField(
            model_name='user',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disttrict',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marrige_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sister',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sister_marrige',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_apply',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
