# Generated by Django 4.2.10 on 2025-03-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0006_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
