# Generated by Django 4.2.10 on 2025-03-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0007_alter_userimages_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User'), ('developer', 'Developer')], default='user', max_length=20),
        ),
    ]
