# Generated by Django 4.2.10 on 2025-04-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.JSONField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='disttrict',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
