# Generated by Django 4.2.10 on 2025-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0009_user_caste_user_state_user_disttrict_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_state',
            name='district',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
