# Generated by Django 4.2.10 on 2025-04-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0010_alter_user_state_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_caste',
            name='caste',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
