# Generated by Django 4.2.10 on 2025-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0011_alter_user_caste_caste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='user_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
