# Generated by Django 4.2.10 on 2025-05-03 10:48

from django.db import migrations, models
import risteyapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0012_alter_userimages_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTotalRevenue',
            fields=[
                ('id', models.CharField(default=risteyapp.utils.secure_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('month', models.DateField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('user', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
