# Generated by Django 4.2.10 on 2025-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0013_usertotalrevenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admintotalrevenue',
            old_name='revenue',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='devtotalrevenue',
            old_name='revenue',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='stafftotalrevenue',
            old_name='revenue',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='usertotalrevenue',
            old_name='revenue',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='usertransactions',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='admintotalrevenue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='devtotalrevenue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stafftotalrevenue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertotalrevenue',
            name='user',
        ),
        migrations.AddField(
            model_name='admintotalrevenue',
            name='admin_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='admintotalrevenue',
            name='date',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='admintotalrevenue',
            name='ruser_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='admintotalrevenue',
            name='suser_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='admintotalrevenue',
            name='user_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devtotalrevenue',
            name='date',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='devtotalrevenue',
            name='dev_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='devtotalrevenue',
            name='ruser_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='devtotalrevenue',
            name='suser_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='devtotalrevenue',
            name='user_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftotalrevenue',
            name='date',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='stafftotalrevenue',
            name='ruser_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='stafftotalrevenue',
            name='staff_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftotalrevenue',
            name='staff_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='stafftotalrevenue',
            name='suser_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='usertotalrevenue',
            name='date',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='usertotalrevenue',
            name='ruser_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='usertotalrevenue',
            name='suser_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='usertotalrevenue',
            name='user_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertotalrevenue',
            name='user_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
