# Generated by Django 4.2.10 on 2025-05-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0014_rename_revenue_admintotalrevenue_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devtotalrevenue',
            old_name='dev_id',
            new_name='dev_amount',
        ),
        migrations.RemoveField(
            model_name='admintotalrevenue',
            name='month',
        ),
        migrations.RemoveField(
            model_name='devtotalrevenue',
            name='month',
        ),
        migrations.RemoveField(
            model_name='devtotalrevenue',
            name='user_amount',
        ),
        migrations.RemoveField(
            model_name='stafftotalrevenue',
            name='month',
        ),
        migrations.RemoveField(
            model_name='stafftotalrevenue',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='usertotalrevenue',
            name='month',
        ),
    ]
