# Generated by Django 4.2.10 on 2025-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0016_devtotalrevenue_month_alter_devtotalrevenue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintotalrevenue',
            name='month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stafftotalrevenue',
            name='month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usertotalrevenue',
            name='month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admintotalrevenue',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stafftotalrevenue',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertotalrevenue',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
