# Generated by Django 4.2.10 on 2025-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0017_admintotalrevenue_month_stafftotalrevenue_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtotalrevenue',
            name='dev_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='stafftotalrevenue',
            name='staff_id',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
