# Generated by Django 4.2.10 on 2025-05-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0018_devtotalrevenue_dev_id_stafftotalrevenue_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admintotalrevenue',
            old_name='user_amount',
            new_name='admin_amount',
        ),
    ]
