# Generated by Django 4.2.10 on 2025-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0019_rename_user_amount_admintotalrevenue_admin_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='status',
            field=models.CharField(default='pending', max_length=8),
        ),
    ]
