# Generated by Django 4.2.10 on 2025-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0020_usertransactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
