# Generated by Django 4.2.10 on 2025-05-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0022_remove_userdata_aadhar_remove_userdata_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transactions',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, default='Staff_Pic/profilepic.jpg', null=True, upload_to='Staff_Pic'),
        ),
    ]
