# Generated by Django 4.2.10 on 2025-05-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0023_remove_user_transactions_user_contact_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='firstname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref',
            field=models.IntegerField(blank=True, default=885695, null=True),
        ),
    ]
