# Generated by Django 4.2.10 on 2025-05-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0024_userdata_firstname_alter_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=20),
        ),
    ]
