# Generated by Django 5.1.1 on 2025-06-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0025_alter_userdata_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='income_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
