# Generated by Django 5.1.1 on 2025-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0026_userdata_education_level_userdata_field_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
