# Generated by Django 5.1.1 on 2025-06-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0027_userdata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cover_img',
            field=models.ImageField(blank=True, default='User_Pic/profilepic.jpg', null=True, upload_to='User_Pic'),
        ),
    ]
