# Generated by Django 5.1.1 on 2025-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0028_userdata_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cover_img',
            field=models.ImageField(blank=True, default='User_Pic/profilecover_pic.jpg', null=True, upload_to='User_Pic'),
        ),
    ]
