# Generated by Django 5.1.1 on 2025-06-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0030_alter_userdata_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='cover_img',
        ),
        migrations.AddField(
            model_name='userimages',
            name='cover_img',
            field=models.ImageField(blank=True, default='User_Pic/profilepic.jpg', null=True, upload_to='User_cover_pic'),
        ),
    ]
