# Generated by Django 5.1.1 on 2025-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0033_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bank_account',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='ifsc_code',
            field=models.CharField(blank=True, default='SBIN0989054', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='upi_id',
            field=models.CharField(blank=True, default='upi_id.oksbi', max_length=15, null=True),
        ),
    ]
