# Generated by Django 5.1.1 on 2025-06-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0034_userdata_bank_account_userdata_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='caste',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
