# Generated by Django 5.1.1 on 2025-06-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risteyapp', '0035_user_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftransactions',
            name='bank_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftransactions',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftransactions',
            name='upi_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='bank_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='upi_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
